### ISSUE TITLE
http://nikolay.rocks/2016-01-13-connect-webpack-to-backend

### ISSUE THREAD

**Issue by henryng24** [MadRabbit/nikolay.rocks#8]
Hey Nikolay! Thanks for sharing this post. I was trying to use it to figure out how I could proxy my webpack server to my express server, though I may have missed something, when you mentioned 
'So, you need to remove all static assets serving from the webpack dev server and leave them to the backend server:'

I'll delete this issue right away or you can close it, but I was hoping you could comment on how to exactly eliminate webpack-dev-server from serving front-end assets, and to instead, delegate that to the back-end.

Honestly... this is probably something that should be a direct message, but unfortunately GitHub doesn't have that capability...

Thank you very much!

**Comment by adriancmiranda** [comment]
@henryng24 This links may help you
http://blog.npirotte.be/a-strong-development-webpack-configuration/
http://blog.npirotte.be/a-strong-webpack-configuration-part-2/
https://github.com/npirotte/webpack-config-example

**Comment by henryng24** [comment]
Thanks @adriancmiranda ! I'll look into it :)

**Comment by kaievns** [comment]
hey henry... apologies for an utterly late comment. long story short i've moved away from that solution eventually. because well, supporting two concerns in the same node app turned to be a lot of headache. i had split the frontend and server side into two apps and it made everything way simpler.

also, docker-compose helped a lot in terms of stopping worrying about how many things i need to boot in order for an entire system to come alive
